name: Code quality check
run-name: Check code quality with linter
on: [push]
jobs:
    Linters:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

            - name: set up JDK
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: 17

            - uses: gradle/gradle-build-action@v3
              with:
                cache-disabled: true

            - name: Detekt
              shell: bash
              run: ./gradlew detekt

            - name: Publish Checkstyle Report
              # You may pin to the exact commit or the version.
              # uses: Juuxel/publish-checkstyle-report@eec483cc03443d79f49d62ccb30da6c210e322f0
              uses: Juuxel/publish-checkstyle-report@v1.0.0
              with:
                # The glob paths to all report XML files
                reports:
                    '**/build/**/detekt.xml'
